 2017-03-11 10:23:04,136 [P9720/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.5.10 application starting on 5CG5264FCM
 2017-03-11 10:23:04,178 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2017-03-11 10:23:04,194 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 16ms)
 2017-03-11 10:23:04,269 [P9720/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2017-03-11 10:23:04,270 [P9720/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2017-03-11 10:23:04,280 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplicationStartupHandler
 2017-03-11 10:23:04,687 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplicationStartupHandler, found 0 (took 407ms)
 2017-03-11 10:23:04,711 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2017-03-11 10:23:04,727 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter, found 0 (took 16ms)
 2017-03-11 10:23:04,728 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2017-03-11 10:23:04,747 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyValueConverter, found 0 (took 19ms)
 2017-03-11 10:23:04,767 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Mvc.SurfaceController
 2017-03-11 10:23:04,784 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Mvc.SurfaceController, found 0 (took 17ms)
 2017-03-11 10:23:04,785 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.WebApi.UmbracoApiController
 2017-03-11 10:23:04,807 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.WebApi.UmbracoApiController, found 0 (took 21ms)
 2017-03-11 10:23:04,859 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IThumbnailProvider
 2017-03-11 10:23:04,871 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IThumbnailProvider, found 0 (took 11ms)
 2017-03-11 10:23:04,872 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IImageUrlProvider
 2017-03-11 10:23:04,883 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IImageUrlProvider, found 0 (took 10ms)
 2017-03-11 10:23:29,840 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:29,841 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:29,936 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2017-03-11 10:23:29,985 [P9720/D2/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Models.PublishedContent.PublishedContentModel, found 0 (took 49ms)
 2017-03-11 10:23:30,047 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:30,047 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:31,047 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:31,047 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:32,047 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:32,047 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:33,063 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:33,064 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:34,064 [P9720/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 10:23:34,064 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 10:23:36,966 [P9720/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2017-03-11 10:23:36,988 [P9720/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2017-03-11 10:23:37,031 [P9720/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2017-03-11 10:23:38,219 [P9720/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2017-03-11 10:23:38,231 [P9720/D2/T1] INFO  DotSee.AutoNode - AutoNode: Loading configuration...
 2017-03-11 10:23:38,231 [P9720/D2/T1] INFO  DotSee.AutoNode - AutoNode: Loading configuration complete
 2017-03-11 10:23:40,176 [P9720/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 36121ms)
 2017-03-11 10:23:40,318 [P9720/D2/T8] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:52441/umbraco (UmbracoModule request)
 2017-03-11 10:23:40,601 [P9720/D2/T8] INFO  umbraco.content - Load Xml from file...
 2017-03-11 10:23:40,606 [P9720/D2/T8] INFO  umbraco.content - Loaded Xml from file.
 2017-03-11 10:23:54,882 [P9720/D2/T8] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IParameterEditor
 2017-03-11 10:23:54,908 [P9720/D2/T8] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IParameterEditor, found 0 (took 26ms)
 2017-03-11 10:24:41,075 [P9720/D2/T14] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2017-03-10 10:24:40
 2017-03-11 10:24:45,021 [P9720/D2/T7] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Persistence.Mappers.BaseMapper
 2017-03-11 10:24:45,051 [P9720/D2/T7] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Persistence.Mappers.BaseMapper, found 0 (took 29ms)
 2017-03-11 10:25:05,981 [P9720/D2/T13] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Umbraco.Core.Persistence.Database.Fetch[T](String sql, Object[] args)
   vid Umbraco.Core.Persistence.Database.Fetch[T](Sql sql)
   vid Umbraco.Core.Sync.DatabaseServerMessenger.ProcessDatabaseInstructions()
   vid Umbraco.Core.Sync.DatabaseServerMessenger.Sync()
   vid Umbraco.Web.BatchedDatabaseServerMessenger.UmbracoModule_RouteAttempt(Object sender, RoutableAttemptEventArgs e)
   vid Umbraco.Web.UmbracoModule.OnRouteAttempt(RoutableAttemptEventArgs args)
   vid Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   vid Umbraco.Web.UmbracoModule.<Init>b__8(Object sender, EventArgs e)
   vid System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   vid System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
ClientConnectionId:c04418f4-23fe-4c5c-bc33-8e4bb24363f1
Error Number:53,State:0,Class:20
 2017-03-11 11:35:42,198 [P9720/D2/T264] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Umbraco.Core.Persistence.Database.Fetch[T](String sql, Object[] args)
   vid Umbraco.Core.Persistence.Database.Fetch[T](Sql sql)
   vid Umbraco.Core.Sync.DatabaseServerMessenger.ProcessDatabaseInstructions()
   vid Umbraco.Core.Sync.DatabaseServerMessenger.Sync()
   vid Umbraco.Web.BatchedDatabaseServerMessenger.UmbracoModule_RouteAttempt(Object sender, RoutableAttemptEventArgs e)
   vid Umbraco.Web.UmbracoModule.OnRouteAttempt(RoutableAttemptEventArgs args)
   vid Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   vid Umbraco.Web.UmbracoModule.<Init>b__8(Object sender, EventArgs e)
   vid System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   vid System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:19:02,520 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2017-03-11 12:19:02,520 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2017-03-11 12:19:02,525 [P9720/D2/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2017-03-11 12:19:02,595 [P9720/D2/T223] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2017-03-11 12:19:02,595 [P9720/D2/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2017-03-11 12:19:02,596 [P9720/D2/T240] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2017-03-11 12:19:02,596 [P9720/D2/T238] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2017-03-11 12:19:02,596 [P9720/D2/T14] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2017-03-11 12:19:02,598 [P9720/D2/T223] INFO  Umbraco.Core.MainDom - Stopping...
 2017-03-11 12:19:02,601 [P9720/D2/T223] INFO  Umbraco.Core.MainDom - Released MainDom.
 2017-03-11 12:19:32,702 [P9720/D2/T242] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: ConfigurationChange

_shutDownMessage=CONFIG change
HostingEnvironment initiated shutdown
CONFIG change
CONFIG change
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
HostingEnvironment orsakade avslut

_shutDownStack=   vid System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   vid System.Environment.get_StackTrace()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   vid System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   vid System.Web.Configuration.HttpConfigurationSystem.OnConfigurationChanged(Object sender, InternalConfigEventArgs e)
   vid System.Configuration.Internal.InternalConfigRoot.OnConfigChanged(InternalConfigEventArgs e)
   vid System.Configuration.BaseConfigurationRecord.OnStreamChanged(String streamname)
   vid System.Web.Configuration.WebConfigurationHostFileChange.OnFileChanged(Object sender, FileChangeEvent e)
   vid System.Web.DirectoryMonitor.FireNotifications()
   vid System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)
   vid System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)
   vid System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   vid System.Threading.ThreadPoolWorkQueue.Dispatch()
   vid System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 2017-03-11 12:21:03,062 [P9720/D3/T228] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.5.10 application starting on 5CG5264FCM
 2017-03-11 12:21:03,080 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2017-03-11 12:21:03,090 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Hash determined (took 10ms)
 2017-03-11 12:21:03,170 [P9720/D3/T228] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2017-03-11 12:21:03,172 [P9720/D3/T228] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2017-03-11 12:21:03,179 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplicationStartupHandler
 2017-03-11 12:21:03,583 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplicationStartupHandler, found 0 (took 403ms)
 2017-03-11 12:21:03,601 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2017-03-11 12:21:03,615 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter, found 0 (took 14ms)
 2017-03-11 12:21:03,616 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2017-03-11 12:21:03,635 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyValueConverter, found 0 (took 19ms)
 2017-03-11 12:21:03,651 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Mvc.SurfaceController
 2017-03-11 12:21:03,664 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Mvc.SurfaceController, found 0 (took 13ms)
 2017-03-11 12:21:03,665 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.WebApi.UmbracoApiController
 2017-03-11 12:21:03,684 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.WebApi.UmbracoApiController, found 0 (took 19ms)
 2017-03-11 12:21:03,722 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IThumbnailProvider
 2017-03-11 12:21:03,738 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IThumbnailProvider, found 0 (took 15ms)
 2017-03-11 12:21:03,739 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IImageUrlProvider
 2017-03-11 12:21:03,756 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IImageUrlProvider, found 0 (took 17ms)
 2017-03-11 12:21:06,518 [P9720/D3/T228] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2017-03-11 12:21:07,363 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2017-03-11 12:21:07,394 [P9720/D3/T228] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Models.PublishedContent.PublishedContentModel, found 0 (took 31ms)
 2017-03-11 12:21:07,475 [P9720/D3/T228] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2017-03-11 12:21:07,503 [P9720/D3/T228] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2017-03-11 12:21:08,934 [P9720/D3/T228] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2017-03-11 12:21:08,947 [P9720/D3/T228] INFO  DotSee.AutoNode - AutoNode: Loading configuration...
 2017-03-11 12:21:08,948 [P9720/D3/T228] INFO  DotSee.AutoNode - AutoNode: Loading configuration complete
 2017-03-11 12:21:10,830 [P9720/D3/T228] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 7834ms)
 2017-03-11 12:21:10,979 [P9720/D3/T219] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:52441/umbraco (UmbracoModule request)
 2017-03-11 12:21:11,172 [P9720/D3/T219] INFO  umbraco.content - Load Xml from file...
 2017-03-11 12:21:11,176 [P9720/D3/T219] INFO  umbraco.content - Loaded Xml from file.
 2017-03-11 12:21:22,329 [P9720/D3/T219] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IParameterEditor
 2017-03-11 12:21:22,352 [P9720/D3/T219] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IParameterEditor, found 0 (took 22ms)
 2017-03-11 12:21:37,833 [P9720/D3/T217] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Persistence.Mappers.BaseMapper
 2017-03-11 12:21:37,861 [P9720/D3/T217] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Persistence.Mappers.BaseMapper, found 0 (took 27ms)
 2017-03-11 12:21:43,870 [P9720/D3/T217] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username nitin from IP address ::1
 2017-03-11 12:21:43,874 [P9720/D3/T217] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: nitin logged in from IP address ::1
 2017-03-11 12:21:47,354 [P9720/D3/T311] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Trees.TreeController
 2017-03-11 12:21:47,394 [P9720/D3/T311] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Trees.TreeController, found 0 (took 40ms)
 2017-03-11 12:21:47,507 [P9720/D3/T217] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplication
 2017-03-11 12:21:47,531 [P9720/D3/T217] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplication, found 0 (took 24ms)
 2017-03-11 12:21:47,622 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.ITree
 2017-03-11 12:21:47,643 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.ITree, found 0 (took 20ms)
 2017-03-11 12:21:47,661 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Trees.TreeController
 2017-03-11 12:21:47,661 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Trees.TreeController, found 0 (took 0ms)
 2017-03-11 12:21:47,664 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.ITree
 2017-03-11 12:21:47,705 [P9720/D3/T242] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.ITree, found 0 (took 40ms)
 2017-03-11 12:22:11,486 [P9720/D3/T224] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2017-03-10 12:22:11
 2017-03-11 12:24:46,701 [P9720/D3/T240] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Kontakta oss' with Id '1201' has been published.
 2017-03-11 12:24:50,143 [P9720/D3/T240] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Database exception occurred
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'id', table 'DB_A16FCD_drakshopDB.dbo.cmsContentVersion'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 299
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Insert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
ClientConnectionId:1e6d6716-743d-43b1-a1ea-3c6472eb9e0f
Error Number:515,State:2,Class:16
 2017-03-11 12:31:13,645 [P9720/D3/T242] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Kontakta oss' with Id '1201' has been published.
 2017-03-11 12:31:17,023 [P9720/D3/T242] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Database exception occurred
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'id', table 'DB_A16FCD_drakshopDB.dbo.cmsContentVersion'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 299
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Insert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
ClientConnectionId:ef3509cf-a62b-4356-9216-b698302fa3fb
Error Number:515,State:2,Class:16
 2017-03-11 12:34:04,351 [P9720/D3/T240] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Kontakta oss' with Id '1272' has been published.
 2017-03-11 12:34:09,572 [P9720/D3/T240] ERROR Umbraco.Core.Persistence.UmbracoDatabase - Database exception occurred
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'id', table 'DB_A16FCD_drakshopDB.dbo.cmsContentVersion'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 299
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClassa.<ExecuteScalarWithRetry>b__9()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteScalarWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.Insert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
ClientConnectionId:f96c45e6-7aad-41f3-b745-21cba3664c2e
Error Number:515,State:2,Class:16
 2017-03-11 12:52:02,352 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2017-03-11 12:52:02,353 [P9720/D3/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2017-03-11 12:52:02,355 [P9720/D3/T242] INFO  Umbraco.Core.MainDom - Stopping...
 2017-03-11 12:52:02,357 [P9720/D3/T309] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2017-03-11 12:52:02,368 [P9720/D3/T240] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2017-03-11 12:52:02,368 [P9720/D3/T255] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2017-03-11 12:52:02,368 [P9720/D3/T256] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2017-03-11 12:52:02,368 [P9720/D3/T224] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2017-03-11 12:52:02,370 [P9720/D3/T242] INFO  Umbraco.Core.MainDom - Released MainDom.
 2017-03-11 12:52:17,107 [P9720/D4/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.5.10 application starting on 5CG5264FCM
 2017-03-11 12:52:17,128 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2017-03-11 12:52:17,139 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 10ms)
 2017-03-11 12:52:17,230 [P9720/D4/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2017-03-11 12:52:17,232 [P9720/D4/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2017-03-11 12:52:17,242 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplicationStartupHandler
 2017-03-11 12:52:17,688 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplicationStartupHandler, found 0 (took 446ms)
 2017-03-11 12:52:17,709 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2017-03-11 12:52:17,726 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter, found 0 (took 17ms)
 2017-03-11 12:52:17,727 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2017-03-11 12:52:17,745 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyValueConverter, found 0 (took 18ms)
 2017-03-11 12:52:17,764 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Mvc.SurfaceController
 2017-03-11 12:52:17,781 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Mvc.SurfaceController, found 0 (took 17ms)
 2017-03-11 12:52:17,782 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.WebApi.UmbracoApiController
 2017-03-11 12:52:17,803 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.WebApi.UmbracoApiController, found 0 (took 20ms)
 2017-03-11 12:52:17,844 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IThumbnailProvider
 2017-03-11 12:52:17,853 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IThumbnailProvider, found 0 (took 8ms)
 2017-03-11 12:52:17,853 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IImageUrlProvider
 2017-03-11 12:52:17,863 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IImageUrlProvider, found 0 (took 9ms)
 2017-03-11 12:52:32,572 [P9720/D3/T308] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: ConfigurationChange

_shutDownMessage=IIS configuration change
HostingEnvironment initiated shutdown
CONFIG change
CONFIG change
CONFIG change
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
Change in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\vs\c26db6eb\7c58bc35\hash\hash.web
Change in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\vs\c26db6eb\7c58bc35\hash\hash.web
HostingEnvironment orsakade avslut

_shutDownStack=   vid System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   vid System.Environment.get_StackTrace()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   vid System.Web.Hosting.PipelineRuntime.StopProcessing()
 2017-03-11 12:52:41,804 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:41,805 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:41,870 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2017-03-11 12:52:41,906 [P9720/D4/T1] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Models.PublishedContent.PublishedContentModel, found 0 (took 36ms)
 2017-03-11 12:52:41,991 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:41,991 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:42,991 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:42,991 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:43,991 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:43,991 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:44,991 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:44,991 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:45,991 [P9720/D4/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: SQL5030.myWindowsHosting.com, InitialCatalog: DB_A16FCD_drakshopDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 12:52:45,991 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2017-03-11 12:52:48,836 [P9720/D4/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2017-03-11 12:52:48,855 [P9720/D4/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2017-03-11 12:52:48,887 [P9720/D4/T1] INFO  DotSee.AutoNode - AutoNode: Loading configuration...
 2017-03-11 12:52:48,887 [P9720/D4/T1] INFO  DotSee.AutoNode - AutoNode: Loading configuration complete
 2017-03-11 12:52:48,899 [P9720/D4/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2017-03-11 12:52:50,300 [P9720/D4/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2017-03-11 12:52:52,333 [P9720/D4/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 35298ms)
 2017-03-11 12:52:52,471 [P9720/D4/T294] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:52441/umbraco (UmbracoModule request)
 2017-03-11 12:52:52,644 [P9720/D4/T294] INFO  umbraco.content - Load Xml from file...
 2017-03-11 12:52:52,646 [P9720/D4/T294] INFO  umbraco.content - Loaded Xml from file.
 2017-03-11 12:52:55,857 [P9720/D4/T218] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IParameterEditor
 2017-03-11 12:52:55,891 [P9720/D4/T218] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IParameterEditor, found 0 (took 33ms)
 2017-03-11 12:53:01,594 [P9720/D4/T224] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Persistence.Mappers.BaseMapper
 2017-03-11 12:53:01,628 [P9720/D4/T224] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Persistence.Mappers.BaseMapper, found 0 (took 34ms)
 2017-03-11 12:53:07,403 [P9720/D4/T224] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username nitin from IP address ::1
 2017-03-11 12:53:07,404 [P9720/D4/T224] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: nitin logged in from IP address ::1
 2017-03-11 12:53:11,399 [P9720/D4/T311] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username nitin from IP address ::1
 2017-03-11 12:53:11,399 [P9720/D4/T311] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: nitin logged in from IP address ::1
 2017-03-11 12:53:13,546 [P9720/D4/T309] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Trees.TreeController
 2017-03-11 12:53:13,564 [P9720/D4/T309] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Trees.TreeController, found 0 (took 18ms)
 2017-03-11 12:53:13,674 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplication
 2017-03-11 12:53:13,710 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplication, found 0 (took 36ms)
 2017-03-11 12:53:13,752 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.ITree
 2017-03-11 12:53:13,771 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.ITree, found 0 (took 18ms)
 2017-03-11 12:53:13,787 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Trees.TreeController
 2017-03-11 12:53:13,787 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Trees.TreeController, found 0 (took 0ms)
 2017-03-11 12:53:13,791 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.ITree
 2017-03-11 12:53:13,817 [P9720/D4/T231] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.ITree, found 0 (took 25ms)
 2017-03-11 12:53:52,940 [P9720/D4/T242] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2017-03-10 12:53:52
 2017-03-11 13:25:45,621 [P9720/D4/T294] ERROR Umbraco.Web.Strategies.ServerRegistrationEventHandler - Failed to update server record in database.
System.Data.SqlClient.SqlException (0x80131904): Det uppstod ett fel på transportnivå när resultat skulle tas emot från servern. (provider: TCP Provider, error: 0 - Tidsgränsen för semaforen har uppnåtts.) ---> System.ComponentModel.Win32Exception (0x80004005): Tidsgränsen för semaforen har uppnåtts
   vid System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   vid System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   vid System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   vid System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   vid System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   vid System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   vid System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   vid System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   vid System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   vid System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   vid System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   vid System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   vid System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction(TransactionRequest transactionRequest, String name, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   vid System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   vid System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   vid System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   vid System.Data.Common.DbConnection.System.Data.IDbConnection.BeginTransaction(IsolationLevel isolationLevel)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.BeginTransaction(IsolationLevel isolationLevel)
   vid Umbraco.Core.Persistence.LockingRepository`1.WithWriteLocked(Action`1 action, Boolean autoCommit)
   vid Umbraco.Core.Services.ServerRegistrationService.TouchServer(String serverAddress, String serverIdentity, TimeSpan staleTimeout)
   vid Umbraco.Web.Strategies.ServerRegistrationEventHandler.TouchServerTask.PerformRun()
ClientConnectionId:012435e0-c676-4dac-900b-95f49dea1360
Error Number:121,State:0,Class:20
 2017-03-11 13:25:50,688 [P9720/D4/T309] ERROR Umbraco.Web.Scheduling.ScheduledPublishing - Failed (at "http://localhost:52441/umbraco").
System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.<Query>d__1c`1.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Umbraco.Core.Persistence.Database.Fetch[T1,T2,TRet](Func`3 cb, Sql sql)
   vid Umbraco.Core.Persistence.Repositories.UserRepository.PerformGet(Int32 id)
   vid Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Get(TId id, Func`2 getFromRepo)
   vid Umbraco.Core.Persistence.Repositories.RepositoryBase`2.Get(TId id)
   vid Umbraco.Core.Services.UserService.GetUserById(Int32 id)
   vid Umbraco.Web.Mvc.AdminTokenAuthorizeAttribute.GetAuthHeaderVal(ApplicationContext appContext)
   vid Umbraco.Web.Mvc.AdminTokenAuthorizeAttribute.GetAuthenticationHeaderValue(ApplicationContext appContext)
   vid Umbraco.Web.Scheduling.ScheduledPublishing.<PerformRunAsync>d__7.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 13:25:50,689 [P9720/D4/T241] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Umbraco.Core.Persistence.Database.Fetch[T](String sql, Object[] args)
   vid Umbraco.Core.Persistence.Database.Fetch[T](Sql sql)
   vid Umbraco.Core.Sync.DatabaseServerMessenger.ProcessDatabaseInstructions()
   vid Umbraco.Core.Sync.DatabaseServerMessenger.Sync()
   vid Umbraco.Web.BatchedDatabaseServerMessenger.UmbracoModule_RouteAttempt(Object sender, RoutableAttemptEventArgs e)
   vid Umbraco.Web.UmbracoModule.OnRouteAttempt(RoutableAttemptEventArgs args)
   vid Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   vid Umbraco.Web.UmbracoModule.<Init>b__8(Object sender, EventArgs e)
   vid System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   vid System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 13:27:05,227 [P9720/D4/T309] ERROR Umbraco.Web.Scheduling.ScheduledPublishing - Failed (at "http://localhost:52441/umbraco").
System.Data.SqlClient.SqlException (0x80131904): Ett nätverksrelaterat eller instansspecifikt fel uppstod när en anslutning skulle upprättas till SQL Server. Servern hittades inte eller var inte tillgänglig. Kontrollera att instansnamnet är korrekt och att SQL Server är konfigurerad till att tillåta fjärranslutningar. (provider: Named Pipes Provider, error: 40 - Det gick inte att öppna en anslutning till SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): Nätverkssökvägen kan inte hittas
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   vid Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.<Query>d__1c`1.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Umbraco.Core.Persistence.Database.Fetch[T1,T2,TRet](Func`3 cb, Sql sql)
   vid Umbraco.Core.Persistence.Repositories.UserRepository.PerformGet(Int32 id)
   vid Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Get(TId id, Func`2 getFromRepo)
   vid Umbraco.Core.Persistence.Repositories.RepositoryBase`2.Get(TId id)
   vid Umbraco.Core.Services.UserService.GetUserById(Int32 id)
   vid Umbraco.Web.Mvc.AdminTokenAuthorizeAttribute.GetAuthHeaderVal(ApplicationContext appContext)
   vid Umbraco.Web.Mvc.AdminTokenAuthorizeAttribute.GetAuthenticationHeaderValue(ApplicationContext appContext)
   vid Umbraco.Web.Scheduling.ScheduledPublishing.<PerformRunAsync>d__7.MoveNext()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
 2017-03-11 13:55:12,773 [P9720/D4/T273] INFO  Umbraco.Core.MainDom - Stopping...
 2017-03-11 13:55:12,780 [P9720/D4/T273] INFO  Umbraco.Core.MainDom - Released MainDom.
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
 2017-03-11 13:55:12,782 [P9720/D4/T285] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated
 2017-03-11 13:55:12,782 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
 2017-03-11 13:55:12,793 [P9720/D4/T295] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
 2017-03-11 13:55:12,840 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
 2017-03-11 13:55:12,840 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
 2017-03-11 13:55:12,840 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
 2017-03-11 13:55:12,840 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
 2017-03-11 13:55:12,840 [P9720/D4/T242] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
 2017-03-11 13:55:12,840 [P9720/D4/T273] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
 2017-03-11 13:55:42,921 [P9720/D4/T292] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: BinDirChangeOrDirectoryRename

_shutDownMessage=Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
HostingEnvironment initiated shutdown
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
Ändringsaviseringar för viktiga kataloger.
bin dir change or directory rename
HostingEnvironment orsakade avslut

_shutDownStack=   vid System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   vid System.Environment.get_StackTrace()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   vid System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   vid System.Web.HttpRuntime.OnCriticalDirectoryChange(Object sender, FileChangeEvent e)
   vid System.Web.FileChangesMonitor.OnCriticaldirChange(Object sender, FileChangeEvent e)
   vid System.Web.DirectoryMonitor.FireNotifications()
   vid System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)
   vid System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)
   vid System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   vid System.Threading.ThreadPoolWorkQueue.Dispatch()
   vid System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
